const express = require('express');
const router = express.Router();
const { body, param, validationResult } = require('express-validator');
const fabricClient = require('../utils/fabricClient');
const logger = require('../utils/logger');
const { requireMSP, optionalMSP, requireHandoverReceiver } = require('../middleware/mspValidation');
const { generateHandoverRequestSignature, generateHandoverAcceptSignature, generateHandoverRejectSignature } = require('../utils/signatureHelper');

const CHANNEL_NAME = process.env.CHANNEL_NAME || 'supplychain-channel';
const CHAINCODE_NAME = process.env.CHAINCODE_NAME || 'supplychain_cc';

// Validation middleware
const validate = (req, res, next) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.status(400).json({
            success: false,
            errors: errors.array()
        });
    }
    next();
};

/**
 * @route   POST /api/v2/handovers/manufacturer-shipper
 * @desc    Request handover from Manufacturer to Shipper (AUTO-GENERATES SIGNATURE)
 * @access  Private (Manufacturer MSP only)
 * @workflow Step 1 of 2-party approval
 * @security MSP validation enforced - only OrgManufacturerMSP allowed
 * @body {string} productId - Product ID
 * @body {string} shipperId - Shipper ID
 * @body {string} waybill - Waybill number
 * @note Signature is auto-generated by backend, no need to send from UI
 */
router.post('/manufacturer-shipper',
    requireMSP('manufacturer'),
    [
        body('productId').notEmpty().withMessage('Product ID is required'),
        body('shipperId').notEmpty().withMessage('Shipper ID is required'),
        body('waybill').notEmpty().withMessage('Waybill is required')
    ],
    validate,
    async (req, res) => {
        try {
            const { productId, shipperId, waybill } = req.body;
            const userIdentity = req.headers['x-user-identity'];
            const [org, userId] = userIdentity.split(':');

            logger.info(`[Handover] Manufacturer requesting handover to shipper for product ${productId}`);

            // AUTO-GENERATE SIGNATURE (no need for UI to provide)
            const signature = await generateHandoverRequestSignature(org, userId, productId, 'shipper');
            logger.info(`[Handover] Auto-generated signature: ${signature.length} chars`);

            // Submit transaction to blockchain
            await fabricClient.submitTransaction(
                CHANNEL_NAME,
                CHAINCODE_NAME,
                'RequestHandoverToShipper',
                productId,
                shipperId,
                waybill,
                signature
            );

            // Query the product to get the actual handover ID (includes TxID suffix)
            // Product.pendingHandover is updated with the real handover ID
            await new Promise(resolve => setTimeout(resolve, 500));

            const productResult = await fabricClient.evaluateTransaction(
                CHANNEL_NAME,
                CHAINCODE_NAME,
                'GetProduct',
                productId
            );

            const product = productResult ? JSON.parse(productResult.toString()) : null;
            const handoverId = product && product.pendingHandover ?
                product.pendingHandover :
                `HANDOVER-${productId}-SHIPPER`;

            logger.info(`[Handover] Created: ${handoverId}`);

            res.status(201).json({
                success: true,
                message: 'Handover request created successfully',
                data: {
                    handoverId,
                    productId,
                    fromOrg: 'Manufacturer',
                    toOrg: 'Shipper',
                    status: 'PENDING',
                    metadata: {
                        shipperId,
                        waybill
                    }
                }
            });

        } catch (error) {
            logger.error('[Handover] Error requesting manufacturer-shipper handover:', error);

            // Parse specific errors
            if (error.message.includes('unauthorized')) {
                return res.status(403).json({
                    success: false,
                    error: 'Unauthorized: Only manufacturer can request this handover'
                });
            }
            if (error.message.includes('already has pending handover')) {
                return res.status(409).json({
                    success: false,
                    error: 'Product already has a pending handover'
                });
            }
            if (error.message.includes('must be in Manufactured state')) {
                return res.status(400).json({
                    success: false,
                    error: 'Product must be in Manufactured state'
                });
            }

            res.status(500).json({
                success: false,
                error: error.message
            });
        }
    }
);

/**
 * @route   POST /api/v2/handovers/shipper-warehouse
 * @desc    Request handover from Shipper to Warehouse (AUTO-GENERATES SIGNATURE)
 * @access  Private (Shipper MSP only)
 * @workflow Step 1 of 2-party approval
 * @security MSP validation enforced - only OrgShipperMSP allowed
 * @body {string} productId - Product ID
 * @body {string} warehouseId - Warehouse ID
 * @note Signature is auto-generated by backend
 */
router.post('/shipper-warehouse',
    requireMSP('shipper'),
    [
        body('productId').notEmpty().withMessage('Product ID is required'),
        body('warehouseId').notEmpty().withMessage('Warehouse ID is required')
    ],
    validate,
    async (req, res) => {
        try {
            const { productId, warehouseId } = req.body;
            const userIdentity = req.headers['x-user-identity'];
            const [org, userId] = userIdentity.split(':');

            logger.info(`[Handover] Shipper requesting handover to warehouse for product ${productId}`);

            // AUTO-GENERATE SIGNATURE
            const signature = await generateHandoverRequestSignature(org, userId, productId, 'warehouse');
            logger.info(`[Handover] Auto-generated signature: ${signature.length} chars`);

            // Submit transaction to blockchain
            await fabricClient.submitTransaction(
                CHANNEL_NAME,
                CHAINCODE_NAME,
                'RequestHandoverToWarehouse',
                productId,
                warehouseId,
                signature
            );

            // Query the product to get the actual handover ID (includes TxID suffix)
            await new Promise(resolve => setTimeout(resolve, 500));

            const productResult = await fabricClient.evaluateTransaction(
                CHANNEL_NAME,
                CHAINCODE_NAME,
                'GetProduct',
                productId
            );

            const product = productResult ? JSON.parse(productResult.toString()) : null;
            const handoverId = product && product.pendingHandover ?
                product.pendingHandover :
                `HANDOVER-${productId}-WAREHOUSE`;

            logger.info(`[Handover] Created: ${handoverId}`);

            res.status(201).json({
                success: true,
                message: 'Handover request created successfully',
                data: {
                    handoverId,
                    productId,
                    fromOrg: 'Shipper',
                    toOrg: 'Warehouse',
                    status: 'PENDING',
                    metadata: {
                        warehouseId
                    }
                }
            });

        } catch (error) {
            logger.error('[Handover] Error requesting shipper-warehouse handover:', error);

            // Parse specific errors
            if (error.message.includes('unauthorized')) {
                return res.status(403).json({
                    success: false,
                    error: 'Unauthorized: Only shipper can request this handover'
                });
            }
            if (error.message.includes('already has pending handover')) {
                return res.status(409).json({
                    success: false,
                    error: 'Product already has a pending handover'
                });
            }
            if (error.message.includes('must be in InTransit or Shipped state')) {
                return res.status(400).json({
                    success: false,
                    error: 'Product must be in transit or shipped state'
                });
            }

            res.status(500).json({
                success: false,
                error: error.message
            });
        }
    }
);

/**
 * @route   POST /api/v2/handovers/:id/accept
 * @desc    Accept handover (AUTO-GENERATES NONCE-BASED SIGNATURE)
 * @access  Private (ToOrg MSP: Shipper, Warehouse, or Retailer)
 * @workflow Step 2 of 2-party approval
 * @security Dynamic MSP validation - only handover recipient can accept
 * @body {string} receiverId - ID of person/entity receiving (e.g., DRIVER-001)
 * @note Fetches nonce from blockchain and auto-generates signature
 */
router.post('/:id/accept',
    requireHandoverReceiver,
    [
        param('id').notEmpty().withMessage('Handover ID is required'),
        body('receiverId').notEmpty().withMessage('Receiver ID is required')
    ],
    validate,
    async (req, res) => {
        try {
            const { id } = req.params;
            const { receiverId } = req.body;
            const userIdentity = req.headers['x-user-identity'];
            const [org, userId] = userIdentity.split(':');

            logger.info(`[Handover] Accepting handover: ${id}`);

            // STEP 1: Get handover details to extract nonce
            const handoverResult = await fabricClient.evaluateTransaction(
                CHANNEL_NAME,
                CHAINCODE_NAME,
                'GetHandover',
                id
            );

            const handover = handoverResult ? JSON.parse(handoverResult.toString()) : null;
            if (!handover || !handover.nonce) {
                return res.status(404).json({
                    success: false,
                    error: 'Handover not found or missing nonce'
                });
            }

            logger.info(`[Handover] Retrieved nonce: ${handover.nonce.substring(0, 40)}...`);

            // STEP 2: AUTO-GENERATE SIGNATURE with nonce
            const signature = await generateHandoverAcceptSignature(org, userId, id, handover.nonce, receiverId);
            logger.info(`[Handover] Auto-generated acceptance signature: ${signature.length} chars`);

            // Submit transaction to blockchain
            await fabricClient.submitTransaction(
                CHANNEL_NAME,
                CHAINCODE_NAME,
                'AcceptHandover',
                id,
                receiverId,
                signature
            );

            logger.info(`[Handover] Accepted: ${id}`);

            res.status(200).json({
                success: true,
                message: 'Handover accepted successfully',
                data: {
                    handoverId: id,
                    status: 'ACCEPTED',
                    acceptedAt: new Date().toISOString()
                }
            });

        } catch (error) {
            logger.error(`[Handover] Error accepting handover ${req.params.id}:`, error);

            // Parse specific errors
            if (error.message.includes('unauthorized') || error.message.includes('cannot accept')) {
                return res.status(403).json({
                    success: false,
                    error: 'Unauthorized: You cannot accept this handover'
                });
            }
            if (error.message.includes('not in pending state')) {
                return res.status(409).json({
                    success: false,
                    error: 'Handover is not in pending state'
                });
            }
            if (error.message.includes('does not exist')) {
                return res.status(404).json({
                    success: false,
                    error: 'Handover not found'
                });
            }

            res.status(500).json({
                success: false,
                error: error.message
            });
        }
    }
);

/**
 * @route   POST /api/v2/handovers/:id/reject
 * @desc    Reject handover (AUTO-GENERATES NONCE-BASED SIGNATURE)
 * @access  Private (ToOrg MSP: Shipper, Warehouse, or Retailer)
 * @workflow Step 2 alternative (rejection)
 * @security Dynamic MSP validation - only handover recipient can reject
 * @body {string} reason - Reason for rejection
 * @note Fetches nonce from blockchain and auto-generates signature
 */
router.post('/:id/reject',
    requireHandoverReceiver,
    [
        param('id').notEmpty().withMessage('Handover ID is required'),
        body('reason').notEmpty().withMessage('Rejection reason is required')
    ],
    validate,
    async (req, res) => {
        try {
            const { id } = req.params;
            const { reason } = req.body;
            const userIdentity = req.headers['x-user-identity'];
            const [org, userId] = userIdentity.split(':');

            logger.info(`[Handover] Rejecting handover: ${id}, reason: ${reason}`);

            // STEP 1: Get handover details to extract nonce
            const handoverResult = await fabricClient.evaluateTransaction(
                CHANNEL_NAME,
                CHAINCODE_NAME,
                'GetHandover',
                id
            );

            const handover = handoverResult ? JSON.parse(handoverResult.toString()) : null;
            if (!handover || !handover.nonce) {
                return res.status(404).json({
                    success: false,
                    error: 'Handover not found or missing nonce'
                });
            }

            // STEP 2: AUTO-GENERATE SIGNATURE with nonce
            const signature = await generateHandoverRejectSignature(org, userId, id, handover.nonce);
            logger.info(`[Handover] Auto-generated rejection signature: ${signature.length} chars`);

            // Submit transaction to blockchain
            await fabricClient.submitTransaction(
                CHANNEL_NAME,
                CHAINCODE_NAME,
                'RejectHandover',
                id,
                reason,
                signature
            );

            logger.info(`[Handover] Rejected: ${id}`);

            res.status(200).json({
                success: true,
                message: 'Handover rejected successfully',
                data: {
                    handoverId: id,
                    status: 'REJECTED',
                    rejectedAt: new Date().toISOString(),
                    reason
                }
            });

        } catch (error) {
            logger.error(`[Handover] Error rejecting handover ${req.params.id}:`, error);

            // Parse specific errors
            if (error.message.includes('unauthorized') || error.message.includes('cannot reject')) {
                return res.status(403).json({
                    success: false,
                    error: 'Unauthorized: You cannot reject this handover'
                });
            }
            if (error.message.includes('not in pending state')) {
                return res.status(409).json({
                    success: false,
                    error: 'Handover is not in pending state'
                });
            }
            if (error.message.includes('does not exist')) {
                return res.status(404).json({
                    success: false,
                    error: 'Handover not found'
                });
            }

            res.status(500).json({
                success: false,
                error: error.message
            });
        }
    }
);

/**
 * @route   GET /api/v2/handovers/pending
 * @desc    Get pending handovers for current organization
 * @access  Private (All MSPs - filtered by caller's MSP)
 * @security Optional MSP validation (chaincode filters by MSP)
 */
router.get('/pending', optionalMSP, async (req, res) => {
    try {
        logger.info('[Handover] Fetching pending handovers for organization');

        // Query blockchain
        const result = await fabricClient.evaluateTransaction(
            CHANNEL_NAME,
            CHAINCODE_NAME,
            'GetPendingHandoversForOrg'
        );

        const resultStr = result ? result.toString() : '';
        const handovers = resultStr && resultStr.trim() !== '' ? JSON.parse(resultStr) : [];

        logger.info(`[Handover] Found ${handovers.length} pending handovers`);

        res.status(200).json({
            success: true,
            count: handovers.length,
            data: handovers
        });

    } catch (error) {
        logger.error('[Handover] Error fetching pending handovers:', error);
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

/**
 * @route   GET /api/v2/handovers/:id
 * @desc    Get handover details by ID
 * @access  Private (All MSPs)
 * @security Optional MSP validation (logs identity)
 */
router.get('/:id',
    optionalMSP,
    param('id').notEmpty().withMessage('Handover ID is required'),
    validate,
    async (req, res) => {
        try {
            const { id } = req.params;

            logger.info(`[Handover] Fetching handover details: ${id}`);

            // Query blockchain
            const result = await fabricClient.evaluateTransaction(
                CHANNEL_NAME,
                CHAINCODE_NAME,
                'GetHandover',
                id
            );

            const resultStr = result ? result.toString() : '';
            const handover = resultStr && resultStr.trim() !== '' ? JSON.parse(resultStr) : null;

            if (!handover) {
                return res.status(404).json({
                    success: false,
                    error: 'Handover not found'
                });
            }

            res.status(200).json({
                success: true,
                data: handover
            });

        } catch (error) {
            logger.error(`[Handover] Error fetching handover ${req.params.id}:`, error);

            if (error.message.includes('does not exist')) {
                return res.status(404).json({
                    success: false,
                    error: 'Handover not found'
                });
            }

            res.status(500).json({
                success: false,
                error: error.message
            });
        }
    }
);

module.exports = router;
