services:
  backend:
    build: .
    container_name: iot-backend
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mosquitto
    command: sh -c "npx prisma db push && node prisma/seed.js && node src/server.js"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iotdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

volumes:
  pgdata: {}
  mosquitto_data: {}
  mosquitto_log: {}

